[package]
name = "rustevtx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
evtx = "0.8.1"
xml2json-rs = "1.0.1"
